version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/work
      - vendor-store:/work/backend/vendor # add

  web:
    image: nginx:1.20-alpine
    build:
      context: .
      dockerfile: ./infra/nginx/Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - node_modules-store:/work/backend/node_modules # add
    working_dir: /work

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db-store:
  vendor-store: # add
  node_modules-store: # add